# Use root/example as user/password credentials
version: '3.1'

services:

 database:
    image: mariadb:latest
    hostname: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=auser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=momentum
      - MARIADB_AUTO_UPGRADE=1
    ports:
      - "3306:3306"