# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    image: mariadb:latest
    hostname: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=auser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=momentum
      - MARIADB_AUTO_UPGRADE=1
    ports:
      - "3306:3306"
    # profiles:
    #   - mysql


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    # profiles:
    #   - mongodb
    #   - mdbinterface

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    # profiles:
    #   - mongodb
    #   - mdbinterface

  momentum_gql:
    build:
      context: ./momentum_gql
    ports:
      - "8010:8000"
    environment:
      MDB_INTERFACE_URL: http://host.docker.internal:8011

  mdb_interface:
    build:
        context: ./mdb_interface
    ports:
      - "8011:8000"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      DB_NAME: "Momentum"
    # profiles:
    #   - mdbinterface